"""
GitHub Actions CI/CD Workflow Generator.
"""

import os

GITHUB_ACTIONS_TEMPLATE = """\
# AI DevOps Assistant — Generated GitHub Actions Workflow
name: AI DevOps CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  devops-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install AI DevOps Assistant
        run: |
          pip install ai-devops-assistant
          pip install ruff bandit mypy pylint safety

      - name: Install & Start Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama serve &
          sleep 5
          ollama pull {model}

      - name: Run CI Pipeline
        run: |
          devops-assistant run \\
            --path . \\
            --model {model} \\
            --ollama-url http://localhost:11434 \\
            --output-dir ci_reports

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-report
          path: ci_reports/ci_report.html
          retention-days: 30

      - name: Upload Markdown Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-report-md
          path: ci_reports/ci_report.md
          retention-days: 30
"""

GITLAB_CI_TEMPLATE = """\
# AI DevOps Assistant — Generated GitLab CI Pipeline
stages:
  - audit

variables:
  OLLAMA_MODEL: "{model}"

ai-devops-audit:
  stage: audit
  image: python:3.11-slim
  timeout: 30 minutes
  before_script:
    - pip install ai-devops-assistant ruff bandit mypy pylint safety
    - apt-get update -qq && apt-get install -y -qq curl
    - curl -fsSL https://ollama.com/install.sh | sh
    - ollama serve &
    - sleep 5
    - ollama pull $OLLAMA_MODEL
  script:
    - devops-assistant run --path . --model $OLLAMA_MODEL --output-dir ci_reports
  artifacts:
    when: always
    paths:
      - ci_reports/ci_report.html
      - ci_reports/ci_report.md
    expire_in: 30 days
"""

PRE_COMMIT_TEMPLATE = """\
#!/bin/sh
# AI DevOps Assistant — Pre-commit Hook
# Generated by: devops-assistant generate-ci --platform pre-commit

set -e

echo "🔍 Running AI DevOps pre-commit checks..."

# Get list of staged Python files
STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.py$' || true)

if [ -z "$STAGED" ]; then
    echo "No Python files staged. Skipping."
    exit 0
fi

# Run Ruff on staged files
if command -v ruff >/dev/null 2>&1; then
    echo "Running Ruff..."
    ruff check $STAGED || { echo "❌ Ruff found issues. Fix them before committing."; exit 1; }
fi

# Run Bandit on staged files
if command -v bandit >/dev/null 2>&1; then
    echo "Running Bandit..."
    bandit -q $STAGED || true  # Warn only, don't block
fi

echo "✅ Pre-commit checks passed."
"""


def generate_github_actions(output_dir: str = ".", model: str = "qwen2.5-coder") -> str:
    """Generate a GitHub Actions workflow file."""
    gh_dir = os.path.join(output_dir, ".github", "workflows")
    os.makedirs(gh_dir, exist_ok=True)
    path = os.path.join(gh_dir, "devops-assistant.yml")
    with open(path, "w") as f:
        f.write(GITHUB_ACTIONS_TEMPLATE.format(model=model))
    return path


def generate_gitlab_ci(output_dir: str = ".", model: str = "qwen2.5-coder") -> str:
    """Generate a GitLab CI pipeline file."""
    path = os.path.join(output_dir, ".gitlab-ci.yml")
    with open(path, "w") as f:
        f.write(GITLAB_CI_TEMPLATE.format(model=model))
    return path


def generate_pre_commit_hook(output_dir: str = ".") -> str:
    """Generate a git pre-commit hook script."""
    hooks_dir = os.path.join(output_dir, ".git", "hooks")
    os.makedirs(hooks_dir, exist_ok=True)
    path = os.path.join(hooks_dir, "pre-commit")
    with open(path, "w") as f:
        f.write(PRE_COMMIT_TEMPLATE)
    # Make executable on Unix
    try:
        os.chmod(path, 0o755)
    except Exception:
        pass
    return path
